<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitda435fa973ac131cd03e37d810c45684
{
    public static $prefixLengthsPsr4 = array (
        'n' =>
        array (
            'nadar\\quill\\' => 12,
        ),
        'L' =>
        array (
            'Lizas\\Localhost\\' => 16,
        ),
        'E' =>
        array (
            'Everyday\\QuillDelta\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'nadar\\quill\\' =>
        array (
            0 => __DIR__ . '/..' . '/nadar/quill-delta-parser/src',
        ),
        'Lizas\\Localhost\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'Everyday\\QuillDelta\\' =>
        array (
            0 => __DIR__ . '/..' . '/everyday/php-quill-delta/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitda435fa973ac131cd03e37d810c45684::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitda435fa973ac131cd03e37d810c45684::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitda435fa973ac131cd03e37d810c45684::$classMap;

        }, null, ClassLoader::class);
    }
}
