<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'nadar\\quill\\' => array($vendorDir . '/nadar/quill-delta-parser/src'),
    'Lizas\\Localhost\\' => array($baseDir . '/src'),
    'Everyday\\QuillDelta\\' => array($vendorDir . '/everyday/php-quill-delta/src'),
);
